# GitLab Pipeline for praise-wm

variables:
  MYSQL_ROOT_PASSWORD: praisewm
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  MYSQL_USER: 'praisewm'
  MYSQL_PASSWORD: 'praisewm'
  MYSQL_DATABASE: 'praisewm'
#  See application.properties for information on PRAISEWM_DATABASE_HOST
  PRAISEWM_DATABASE_HOST: 'praisewm'
  REGISTRY_URI: 'worldmodelers.cse.sri.com/praise-wm'
  BUILD_TAG: '$CI_COMMIT_REF_NAME'
  JAVA_OPTIONS: "-Djava.awt.headless=true"

cache:
  paths:
    - .gradle

stages:
  - buildClient
  - buildServer
  - deployAny
  - deployMaster

buildClient:
  stage: buildClient
  tags:
    - shared
  image: node:10.15.3
  script:
    - cd src/main/webapp
    - yarn
    - yarn lint
    - yarn test:unit
    - yarn build
  retry: 2
  artifacts:
    paths:
      - src/main/webapp/dist
    expire_in: 1 hour

buildServer:
  stage: buildServer
  tags:
    - shared
  image: openjdk:11.0.2-jdk-slim
  dependencies:
    - buildClient
  services:
    - name: mysql:5.7.18
      alias: praisewm
  script:
    - echo -e "\norg.gradle.daemon=false" >> ./gradle.properties
    - ./gradlew
    - ./gradlew compileJava
    - ./gradlew test
    - ./gradlew copyClientResourcesNoBuild
    - ./gradlew shadowJar
  retry: 2
  artifacts:
    paths:
      - build/libs
    expire_in: 1 week

deployAny:
  stage: deployAny
  tags:
    - privileged
  script:
    - cp -vf build/libs/praisewm*all.jar .
    - cp -vf gencerts/keystore.jks .
    - docker build -f src/main/docker/Dockerfile -t $REGISTRY_URI:$BUILD_TAG .
    - docker push $REGISTRY_URI:$BUILD_TAG

deployMaster:
  stage: deployMaster
  tags:
    - privileged
  script:
    - docker pull $REGISTRY_URI:$BUILD_TAG
    - docker tag $REGISTRY_URI:$BUILD_TAG $REGISTRY_URI:latest
    - docker push $REGISTRY_URI:latest
  only:
    refs:
      - master
