kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: praise-wm
resources:
- deploy.yaml
- mysql.yaml
- pvcs.yaml
- ingress.yaml
images:
- name: praise-wm-placeholder
  newName: worldmodelers.cse.sri.com/praise-wm
  newTag: master.2
